name: Deploy to EC2
name: Deploy to VPS
on:
  workflow_dispatch:
    branches:
      - main
env:
  NODE_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Build application
      run: npm run build
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        source: ./dist
        target: /home/express-api/dist
    # - name: Restart node.js application
    #   run: ssh ${{ secrets.USER }}@${{ secrets.HOST }} 'sudo pm2 restart /home/express-api/dist/src/main.js'

