name: Deploy to VPS
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: 'dist/*'
          target: '/home/github/expense-api'
